apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: infrastructure-cluster-services
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/testing
  prune: true
  wait: true
