apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 24h
  values:
    controller:
      service:
        type: "NodePort"
        nodePorts:
          http: "30080"
          https: "30443"
      healthCheckPath:
        "/healthz"
    admissionWebhooks:
      enabled: false
