apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 30m
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: "6.5.*"
      sourceRef:
        kind: HelmRepository
        name: podinfo
  install:
    remediation:
      retries: 3
  values:
#    redis:
#      enabled: true
#      repository: public.ecr.aws/docker/library/redis
#      tag: 7.0.7
#    serviceMonitor:
#      enabled: true
#      interval: 15s
#      additionalLabels: {}
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - host: ""
          paths:
            - path: /podinfo(/|$)(.*)
              pathType: ImplementationSpecific
