apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=2
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=20s
    target:
      kind: Deployment
      name: "source-controller"
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=4
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=10s
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller)"

